version: '3'
services:
  db:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./config/mysql-data:/var/lib/mysql
    env_file:
      - .env      
  baul:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - static:/static
        - .:/baul
      depends_on:
        - db
      env_file: 
      - .env

  nginx: 
      image: nginx:1.21
      ports:
          - 8000:80
      volumes:   
          - ./config/nginx/:/etc/nginx/config.d
          - static:/static
      depends_on:
        - baul
volumes:
  .:
  mysql-data:
  static:
