# Generated by Django 3.1.7 on 2022-03-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomodel',
            name='id_motivo',
            field=models.IntegerField(choices=[(1, 'Niño'), (2, 'Niña')], db_column='id_motivo'),
        ),
    ]
