# Generated by Django 3.1.7 on 2022-01-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('subtotal', models.BigIntegerField(db_column='subtotal')),
                ('total', models.BigIntegerField(db_column='total')),
                ('envio', models.BigIntegerField(db_column='envio')),
                ('estado', models.IntegerField(choices=[(1, 'Cotizada'), (2, 'Facturada')], db_column='estado', default=1)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso')),
                ('adjunto', models.FileField(blank=True, db_column='adjunto', null=True, upload_to='pdf/')),
                ('cliente', models.ForeignKey(db_column='cliente', on_delete=django.db.models.deletion.CASCADE, to='cliente.clientemodel')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'cotizaciones',
                'db_table': 'cotizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacionModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('cantidad', models.BigIntegerField(db_column='cantidad')),
                ('valor', models.BigIntegerField(db_column='valor')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso')),
                ('id_cotizacion', models.ForeignKey(db_column='id_cotizacion', on_delete=django.db.models.deletion.CASCADE, to='cotizacion.cotizacionmodel')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='producto.productomodel')),
            ],
            options={
                'verbose_name': 'Detalle cotizacion',
                'verbose_name_plural': 'Detalle cotizacion',
                'db_table': 'detalle_cotizacion',
                'managed': True,
            },
        ),
    ]
