# Generated by Django 3.1.7 on 2022-01-27 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('modulo', models.CharField(db_column='modulo', max_length=300)),
                ('request', models.CharField(blank=True, db_column='request', max_length=800, null=True)),
                ('excepcion', models.CharField(db_column='excepcion', max_length=600)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'db_table': 'log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificacionModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('modulo', models.CharField(db_column='modulo', max_length=300)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=800, null=True)),
                ('estado', models.BooleanField(db_column='estado', max_length=600)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, db_column='fecha_ingreso')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.stockmodel')),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notificacion',
                'managed': True,
            },
        ),
    ]
